'use client'
import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import AppLayout from '@/components/AppLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: ReactNode
  session: any
}) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <AppLayout>{children}</AppLayout>
        </body>
      </SessionProvider>
    </html>
  )
}
